title:              Art of Active Ageing Foundation
email:              artofactiveageing@gmail.com
description:        Residential Wellness Center & Daycare for Senior Citizens
author:             Rekha Singh
baseurl:            "artofactiveageing.org"
url:                "https://artofactiveageing.org"

# Social Profiles
# twitter_username:   SBootstrap
# github_username:    StartBootstrap
facebook_username:  artofactiveageing
instagram_username:  artofactiveageing
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
